### ISSUE TITLE
Implement problem description rendering

### ISSUE THREAD

**Issue by enjolras** [TheOnlineJudge/ojudge#27]
The problems are stored as LaTeX/PDF files. A way to directly render that as HTML must be found, to avoid having duplicated HTML/PDF versions. Some possible solutions are:

- MathJax
- PDF.js
- pdf2htmlEX

Open to discussion.

**Comment by ProBeta1** [comment]
I think MathJax would be a nice option ..

**Comment by enjolras** [comment]
Yes, MathJax is probably the best option for the problems already formatted in LaTeX. That leaves the ones that are not in LaTeX (that can ultimately be PDFs easily, whether they come from Word or any other format) still to solve, at least until all problems are in LaTeX. Also, when we set up contests that come from other sources, most of the times are not LaTeX either. Let's say that we will go the MathJax way, but some Plan B is still needed (where PDF.js is, probably, the winner here, as it is actively maintained, as opposed to pdf2htmlEX, which is a great piece of software but will little to none upstream support and that can't even be compiled using the latest poppler and other support libraries). There are some dockers around with working pdf2htmlEX, which could serve as an interim, "emergency" solution.

**Comment by enjolras** [comment]
Implemented a problem viewer based in MathJax and the lwarp LaTeX package. Looks like a great solution using well upstream maintained software in #73 . Closing for now.
