### ISSUE TITLE
Building failing with no matching function call to parse_config_file(...)

### ISSUE THREAD

**Issue by sikander441** [TheOnlineJudge/ojudge#51]
[ 95%] Built target ojudge
Scanning dependencies of target ojudgeapp
[ 97%] Building CXX object CMakeFiles/ojudgeapp.dir/ojudge.cpp.o
/home/sikander441/ojudge/ojudge.cpp: In function ‘int main(int, char**)’:
/home/sikander441/ojudge/ojudge.cpp:77:61: error: no matching function for call to ‘parse_config_file(const char*, boost::program_options::options_description&)’
  po::store(po::parse_config_file(configFilePath.c_str(),desc),vm);

**Comment by enjolras** [comment]
Fixed by 9219d3c
