### ISSUE TITLE
Update README file with enough info to run ojudge.

### ISSUE THREAD

**Issue by pkatul** [TheOnlineJudge/ojudge#53]
I am stuck to run ojudge.
I didn't find enough step-by-step to run the OJ from scratch.

**Comment by sikander441** [comment]
there's a quick start thread in google group of ojudge developers

**Comment by enjolras** [comment]
Depends on #54 , which will make the first run a lot easier.

**Comment by enjolras** [comment]
README is more complete. Closing the issue for now, but any further improvements are welcome.
